- id: pre_commit_hook
  name: Check dependencies versions
  description: Checks the commit additions in order to check dependencies versions.
  entry: pre_commit_hook
  language: python
  always_run: true
  minimum_pre_commit_version: '2.0.0'
